### ISSUE TITLE
Problemas no sync

### ISSUE THREAD

**Issue by vanildosouto** [phpdocbrbridge/traducao#101]
Boa tarde, estou tentando rodar a documentação na minha máquina seguindo o passo-a-passo da Wiki, mas quando rodo o comando `php doc-base/configure.php --enable-xml-details --with-lang=pt_BR` ele me retorna o erro abaixo. Tem algum caminho que posso seguir para tentar solucionar esse problema?

PHP version: 7.3.19-1~deb10u1

Checking for source directory... /home/bilbo/dev/github/phpdoc/doc-base
Checking for output filename... /home/bilbo/dev/github/phpdoc/doc-base/.manual.xml
Checking whether to include CHM... no
Checking for PHP executable... /usr/bin/php7.3
Checking for language to build... pt_BR
Checking whether the language is supported... yes
Checking for partial build... no
Checking whether to enable detailed XML error messages... yes
Checking libxml version... 2.9.4
Checking whether to enable detailed error reporting (may segfault)... yes
Checking whether to optimize out the DTD (performance gain, but segfaults)... yes
Generating /home/bilbo/dev/github/phpdoc/doc-base/manual.xml... done
Generating /home/bilbo/dev/github/phpdoc/doc-base/install-unix.xml... done
Generating /home/bilbo/dev/github/phpdoc/doc-base/install-win.xml... done
Generating /home/bilbo/dev/github/phpdoc/doc-base/developer.template.xml... done
Generating /home/bilbo/dev/github/phpdoc/doc-base/scripts/file-entities.php... done
Iterating over extension specific version files... OK
Saving it... OK
Creating file /home/bilbo/dev/github/phpdoc/doc-base/entities/file-entities.ent... done
Checking for if we should generate a simplified file... no
Checking whether to save an invalid .manual.xml... no
Loading and parsing manual.xml... done.
Validating manual.xml... failed.

    The document didn't validate, trying to figure out what went wrong...
(This could take awhile. If you experience segfaults here, try again with --disable-xml-details)

    ERROR (file:////home/bilbo/dev/github/phpdoc/en/reference/componere/book.xml:21:12)
    </para>
    ------------^
    Element include is not declared in para list of possible children

    ERROR (file:////home/bilbo/dev/github/phpdoc/en/reference/componere/book.xml:30:12)
    </para>
    ------------^
    Element include is not declared in para list of possible children

    ERROR (file:////home/bilbo/dev/github/phpdoc/en/reference/componere/book.xml:40:12)
    </para>
    ------------^
    Element include is not declared in para list of possible children

    ERROR (file:////home/bilbo/dev/github/phpdoc/en/reference/componere/book.xml:40:12)
    </para>
    ------------^
    Element include is not declared in para list of possible children

    ERROR (file:////home/bilbo/dev/github/phpdoc/en/reference/parallel/functions/parallel.run.xml:57:12)
    </refentry>
    ------------^
    Element refentry content does not follow the DTD, expecting (indexterm* , info?
            , refmeta? , refnamediv+ , refsynopsisdiv? , (refsection+ | refsect1+)), got
    (refnamediv refsect1 refsect1 xi:include xi:include xi:include xi:include
     xi:include xi:include refsect1 )

    ERROR (file:////home/bilbo/dev/github/phpdoc/en/reference/event/eventbase/dispatch.xml:26:14)
    </warning>
    --------------^
    Element warning content does not follow the DTD, expecting (((title |
                    titleabbrev)* , info?) , (itemizedlist | orderedlist | procedure | simplelist |
                    variablelist | segmentedlist | glosslist | bibliolist | calloutlist | qandaset |
                    caution | important | note | tip | warning | example | figure | table | equation
                    | informalexample | informalfigure | informaltable | informalequation | sidebar
                    | blockquote | address | epigraph | mediaobject | screenshot | task |
                    productionset | constraintdef | msgset | programlisting | screen | literallayout
                    | synopsis | programlistingco | screenco | cmdsynopsis | funcsynopsis |
                    classsynopsis | methodsynopsis | constructorsynopsis | destructorsynopsis |
                    fieldsynopsis | bridgehead | remark | revhistory | indexterm | anchor | para |
                    formalpara | simpara | annotation)+), got (xi:include )

    ERROR (file:////home/bilbo/dev/github/phpdoc/en/reference/event/eventbase/loop.xml:26:14)
    </warning>
    --------------^
    Element warning content does not follow the DTD, expecting (((title |
                    titleabbrev)* , info?) , (itemizedlist | orderedlist | procedure | simplelist |
                    variablelist | segmentedlist | glosslist | bibliolist | calloutlist | qandaset |
                    caution | important | note | tip | warning | example | figure | table | equation
                    | informalexample | informalfigure | informaltable | informalequation | sidebar
                    | blockquote | address | epigraph | mediaobject | screenshot | task |
                    productionset | constraintdef | msgset | programlisting | screen | literallayout
                    | synopsis | programlistingco | screenco | cmdsynopsis | funcsynopsis |
                    classsynopsis | methodsynopsis | constructorsynopsis | destructorsynopsis |
                    fieldsynopsis | bridgehead | remark | revhistory | indexterm | anchor | para |
                    formalpara | simpara | annotation)+), got (xi:include )

    ERROR (file:////home/bilbo/dev/github/phpdoc/en/reference/event/eventbufferevent/sslfilter.xml:127:14)
    </example>
    --------------^
    Element example content does not follow the DTD, expecting (((title |
                    titleabbrev)* , info?) , (itemizedlist | orderedlist | procedure | simplelist |
                    variablelist | segmentedlist | glosslist | bibliolist | calloutlist | qandaset |
                    caution | important | note | tip | warning | example | figure | table | equation
                    | informalexample | informalfigure | informaltable | informalequation | sidebar
                    | blockquote | address | epigraph | mediaobject | screenshot | task |
                    productionset | constraintdef | msgset | programlisting | screen | literallayout
                    | synopsis | programlistingco | screenco | cmdsynopsis | funcsynopsis |
                    classsynopsis | methodsynopsis | constructorsynopsis | destructorsynopsis |
                    fieldsynopsis | bridgehead | remark | revhistory | indexterm | anchor | para |
                    formalpara | simpara | annotation)+ , caption?), got (xi:include )

    ERROR (file:////home/bilbo/dev/github/phpdoc/en/reference/cmark/book.xml:18:12)
    </para>
    ------------^
    Element include is not declared in para list of possible children

    ERROR (file:////home/bilbo/dev/github/phpdoc/en/reference/cmark/book.xml:29:12)
    </para>
    ------------^
    Element include is not declared in para list of possible children

    ERROR (file:////home/bilbo/dev/github/phpdoc/en/reference/cmark/book.xml:29:12)
    </para>
    ------------^
    Element include is not declared in para list of possible children

    ERROR (file:////home/bilbo/dev/github/phpdoc/en/reference/cmark/book.xml:29:12)
    </para>
    ------------^
    Element include is not declared in para list of possible children

    ERROR (file:////home/bilbo/dev/github/phpdoc/en/reference/cmark/book.xml:29:12)
    </para>
    ------------^
    Element include is not declared in para list of possible children

    ERROR (file:////home/bilbo/dev/github/phpdoc/en/reference/cmark/book.xml:29:12)
    </para>
    ------------^
    Element include is not declared in para list of possible children

    ERROR (file:////home/bilbo/dev/github/phpdoc/en/reference/cmark/book.xml:36:12)
    </para>
    ------------^
    Element include is not declared in para list of possible children

    ERROR (file:////home/bilbo/dev/github/phpdoc/en/reference/cmark/book.xml:43:12)
    </para>
    ------------^
    Element include is not declared in para list of possible children
    PHP Notice:  Undefined offset: -1 in /home/bilbo/dev/github/phpdoc/doc-base/configure.php on line 214
    PHP Stack trace:
    PHP   1. {main}() /home/bilbo/dev/github/phpdoc/doc-base/configure.php:0
    PHP   2. print_xml_errors() /home/bilbo/dev/github/phpdoc/doc-base/configure.php:738

ERROR (/home/bilbo/dev/github/phpdoc/doc-base/manual.xml:0:0)

    ^
    IDREF attribute linkend references an unknown ID "ini.safe-mode-exec-dir"

ERROR (/home/bilbo/dev/github/phpdoc/doc-base/manual.xml:25:0)
    %language-snippets.default;
    ^
    IDREF attribute linkend references an unknown ID "ini.safe-mode-exec-dir"

ERROR (/home/bilbo/dev/github/phpdoc/doc-base/manual.xml:unknown)
    IDREF attribute linkend references an unknown ID "ini.safe-mode-exec-dir"
    PHP Notice:  Undefined offset: -1 in /home/bilbo/dev/github/phpdoc/doc-base/configure.php on line 214
    PHP Stack trace:
    PHP   1. {main}() /home/bilbo/dev/github/phpdoc/doc-base/configure.php:0
    PHP   2. print_xml_errors() /home/bilbo/dev/github/phpdoc/doc-base/configure.php:738

ERROR (/home/bilbo/dev/github/phpdoc/doc-base/manual.xml:0:0)

    ^
    IDREF attribute linkend references an unknown ID "features.safe-mode"

ERROR (/home/bilbo/dev/github/phpdoc/doc-base/manual.xml:81:0)
    &language.exceptions;
    ^
    IDREF attribute linkend references an unknown ID "features.safe-mode"
    PHP Notice:  Undefined offset: -1 in /home/bilbo/dev/github/phpdoc/doc-base/configure.php on line 214
    PHP Stack trace:
    PHP   1. {main}() /home/bilbo/dev/github/phpdoc/doc-base/configure.php:0
    PHP   2. print_xml_errors() /home/bilbo/dev/github/phpdoc/doc-base/configure.php:738

ERROR (/home/bilbo/dev/github/phpdoc/doc-base/manual.xml:0:0)

    ^
    IDREF attribute linkend references an unknown ID "features.safe-mode"
    PHP Notice:  Undefined offset: -1 in /home/bilbo/dev/github/phpdoc/doc-base/configure.php on line 214
    PHP Stack trace:
    PHP   1. {main}() /home/bilbo/dev/github/phpdoc/doc-base/configure.php:0
    PHP   2. print_xml_errors() /home/bilbo/dev/github/phpdoc/doc-base/configure.php:738

ERROR (/home/bilbo/dev/github/phpdoc/doc-base/manual.xml:0:0)

    ^
    IDREF attribute linkend references an unknown ID "features.safe-mode"

ERROR (/home/bilbo/dev/github/phpdoc/doc-base/manual.xml:56:0)
    <title>&InstallAndConfigure;</title>
    ^
    IDREF attribute linkend references an unknown ID "features.safe-mode"
    PHP Notice:  Undefined offset: -1 in /home/bilbo/dev/github/phpdoc/doc-base/configure.php on line 214
    PHP Stack trace:
    PHP   1. {main}() /home/bilbo/dev/github/phpdoc/doc-base/configure.php:0
    PHP   2. print_xml_errors() /home/bilbo/dev/github/phpdoc/doc-base/configure.php:738

ERROR (/home/bilbo/dev/github/phpdoc/doc-base/manual.xml:0:0)

    ^
    IDREF attribute linkend references an unknown ID "features.safe-mode"
    PHP Notice:  Undefined offset: -1 in /home/bilbo/dev/github/phpdoc/doc-base/configure.php on line 214
    PHP Stack trace:
    PHP   1. {main}() /home/bilbo/dev/github/phpdoc/doc-base/configure.php:0
    PHP   2. print_xml_errors() /home/bilbo/dev/github/phpdoc/doc-base/configure.php:738

ERROR (/home/bilbo/dev/github/phpdoc/doc-base/manual.xml:0:0)

    ^
    IDREF attribute linkend references an unknown ID "features.safe-mode"

ERROR (/home/bilbo/dev/github/phpdoc/doc-base/manual.xml:unknown)
    IDREF attribute linkend references an unknown ID
    "ini.safe-mode-protected-env-vars"

ERROR (/home/bilbo/dev/github/phpdoc/doc-base/manual.xml:65:0)
    &install.ini;
    ^
    IDREF attribute linkend references an unknown ID "ini.safe-mode-gid"

ERROR (/home/bilbo/dev/github/phpdoc/doc-base/manual.xml:unknown)
    IDREF attribute linkend references an unknown ID "ini.safe-mode-gid"

ERROR (/home/bilbo/dev/github/phpdoc/doc-base/manual.xml:59:0)
    &install.macos.index;
    ^
    IDREF attribute linkend references an unknown ID "ini.safe-mode-include-dir"

ERROR (/home/bilbo/dev/github/phpdoc/doc-base/manual.xml:unknown)
    IDREF attribute linkend references an unknown ID "ini.safe-mode-include-dir"
    PHP Notice:  Undefined offset: -1 in /home/bilbo/dev/github/phpdoc/doc-base/configure.php on line 214
    PHP Stack trace:
    PHP   1. {main}() /home/bilbo/dev/github/phpdoc/doc-base/configure.php:0
    PHP   2. print_xml_errors() /home/bilbo/dev/github/phpdoc/doc-base/configure.php:738

ERROR (/home/bilbo/dev/github/phpdoc/doc-base/manual.xml:0:0)

    ^
    IDREF attribute linkend references an unknown ID "ini.safe-mode"

ERROR (/home/bilbo/dev/github/phpdoc/doc-base/manual.xml:228:0)
    </set>
    ^
    IDREF attribute linkend references an unknown ID "ini.safe-mode"

ERROR (/home/bilbo/dev/github/phpdoc/doc-base/manual.xml:194:0)
    <set xml:id="refs.database">
    ^
    IDREF attribute linkend references an unknown ID "ini.safe-mode"

ERROR (/home/bilbo/dev/github/phpdoc/doc-base/manual.xml:208:0)
    &reference.dbplus.book;
    ^
    IDREF attribute linkend references an unknown ID "ini.safe-mode"

ERROR (/home/bilbo/dev/github/phpdoc/doc-base/manual.xml:222:0)
    &reference.paradox.book;
    ^
    IDREF attribute linkend references an unknown ID "ini.safe-mode"

ERROR (/home/bilbo/dev/github/phpdoc/doc-base/manual.xml:182:0)

    ^
    IDREF attribute linkend references an unknown ID "ini.safe-mode"

ERROR (/home/bilbo/dev/github/phpdoc/doc-base/manual.xml:47:0)
    </book>
    ^
    IDREF attribute linkend references an unknown ID "ini.safe-mode"

ERROR (/home/bilbo/dev/github/phpdoc/doc-base/manual.xml:385:0)
    &reference.cmark.book;
    ^
    IDREF attribute linkend references an unknown ID "ini.safe-mode"

ERROR (/home/bilbo/dev/github/phpdoc/doc-base/manual.xml:unknown)
    IDREF attribute linkend references an unknown ID "ini.safe-mode"

ERROR (/home/bilbo/dev/github/phpdoc/doc-base/manual.xml:unknown)
    IDREF attribute linkend references an unknown ID "ini.safe-mode"

ERROR (/home/bilbo/dev/github/phpdoc/doc-base/manual.xml:unknown)
    IDREF attribute linkend references an unknown ID
    "ini.safe-mode-allowed-env-vars"

    Eyh man. No worries. Happ shittens. Try again after fixing the errors above.

**Comment by alfsb** [comment]
Olá @vanildosouto , boa tarde.

O problema é geral. Algumas dezenas de arquivos no original foram alterados nos últimos dias, e isso quebrou a compilação do manual em Português.

Desses vários problemas, o mais relevante são os "unknown ID". Eu vou tentar resolver isso hoje, mas é literalmente questão de arquivos desatualizados. Ou arquivo que cria o ID faltante desatualizado na tradução, ou arquivos na tradução que referenciam um ID que não existe mais no inglês.

E o procedimento é caçar o ID em ambos, para descobrir qual são os arquivos que precisam ser prioritariamente atualizados.

**Comment by alfsb** [comment]
Corrigi vários problemas, mas infelizmente não vou poder continuar. Caso alguém possa pegar, os arquivos a atualizar são os seguintes:

andre@macrossv:~/phpdoc$ ./find.sh ini.safe-mode
./pt_BR/appendices/migration53.xml:     <link linkend="ini.safe-mode">safe_mode</link>
./pt_BR/reference/curl/constants.xml:     ou <link linkend="ini.safe-mode">safe_mode</link> estiverem ativas.
./pt_BR/reference/mysqli/ini.xml:     <link linkend="ini.safe-mode">safe mode</link>.
./pt_BR/reference/mysqli/ini.xml:     <link linkend="ini.safe-mode">safe mode</link>.
./pt_BR/reference/mysqli/ini.xml:     <link linkend="ini.safe-mode">safe mode</link>.
./pt_BR/reference/misc/functions/highlight-file.xml:      linkend="ini.safe-mode">safe_mode</link> e <link
./pt_BR/reference/mail/functions/mail.xml:        <link linkend="ini.safe-mode">safe_mode</link> e a função
./pt_BR/features/http-auth.xml:    Se <link linkend="ini.safe-mode">modo de segurança</link> estiver habilitado, o 
./pt_BR/language-snippets.ent:<!ENTITY safemode '<link xmlns="http://docbook.org/ns/docbook" linkend="ini.safe-mode">safe mode</link>'>

andre@macrossv:~/phpdoc$ ./find.sh features.safe-mode
./pt_BR/reference/info/functions/putenv.xml:    linkend="features.safe-mode">safe-mode</link> está ativada!
./pt_BR/language-snippets.ent: linkend="features.safe-mode">safe-mode</link> está ativo, o PHP verifica se
./pt_BR/language-snippets.ent: linkend="features.safe-mode">safe-mode</link> está ativo, o PHP verifica se
./pt_BR/language-snippets.ent:<!-- Common pieces in features/safe-mode.xml
./pt_BR/language-snippets.ent:<!ENTITY warn.sm.exec '<warning xmlns="http://docbook.org/ns/docbook"><simpara>With <link linkend="features.safe-mode">safe mode</link> enabled,
./pt_BR/language-snippets.ent:<link linkend="features.safe-mode">safe mode</link> is enabled, you can only
./pt_BR/language-snippets.ent:linkend="features.safe-mode">safe mode</link>.'>

O tratamento do pt_BR/language-snippets.ent é um pouco diferente. Como ele está muito para trás, o procedimento nesse caso é copiar a entidade inteira, se faltando, ou se entidade presente que referencia ID que não existe mais no en/, daí trocar o <link> por um <literal>.

Sim, eu sei que é chato traduzir sem o manual estar compilando, mas essa é a situação atual até consertar todos os erros de desatualização.

**Comment by vanildosouto** [comment]
Só para ter certeza, eu fiz essa alteração no migration53.xml, o caminho é esse mesmo?

```diff
diff --git a/pt_BR/appendices/migration53.xml b/pt_BR/appendices/migration53.xml
index 6671ec7..30320e8 100644
--- a/pt_BR/appendices/migration53.xml
+++ b/pt_BR/appendices/migration53.xml
@@ -579,7 +579,7 @@ try {
    </listitem>
    <listitem>
     <simpara>
-     <link linkend="ini.safe-mode">safe_mode</link>
+     safe_mode
     </simpara>
    </listitem>
    <listitem>
```

**Comment by alfsb** [comment]
On Thu, Oct 15, 2020 at 1:39 PM Vanildo Souto Mangueira <
notifications@github.com> wrote:

> Só para ter certeza, eu fiz essa alteração no migration53.xml, o caminho é
> esse mesmo?
>
> diff --git a/pt_BR/appendices/migration53.xml b/pt_BR/appendices/migration53.xml
>
> index 6671ec7..30320e8 100644
> --- a/pt_BR/appendices/migration53.xml
> +++ b/pt_BR/appendices/migration53.xml
> @@ -579,7 +579,7 @@ try {
>
>     </listitem>
>
>     <listitem>
>
>      <simpara>
> -     <link linkend="ini.safe-mode">safe_mode</link>
> +     safe_mode
>
>
Sim... Foi essa a alteração, afinal, que foi feita no original.

Ver:
http://svn.php.net/viewvc/phpdoc/en/trunk/appendices/migration53.xml?r1=350650&r2=350871&view=patch

André

**Comment by vanildosouto** [comment]
Boa, valeu

**Comment by alfsb** [comment]
Os arquivos que for fazendo, vai dando commit e push, sem dó. Para eu ter noção até onde você já foi, quando eu puder pegar de volta.

**Comment by vanildosouto** [comment]
Por enquanto deu pra fazer isso aqui: https://github.com/phpdocbrbridge/traducao/pull/104

Vou fazer mais hoje a noite

**Comment by vanildosouto** [comment]
Arruma mais um arquivo: https://github.com/phpdocbrbridge/traducao/pull/105

**Comment by vanildosouto** [comment]
Só pra avisar também que a Hacktoberfest desse ano é opt-in, tem que colocar o tópico `hacktoberfest` no repositório. Isso pode trazer mais gente pra ajudar

**Comment by alfsb** [comment]
Manual compilando novamente, `hacktoberfest` acrescentado no tópico, ainda que tardiamente.

No último merge eu notei que o CI deu erro de compilação, porém localmente está passando local.

Isso dito, fechando o issue, que a compilação principal segue normal.
