### ISSUE TITLE
Pedido de permissão para alterar a wiki

### ISSUE THREAD

**Issue by rogeriopradoj** [phpdocbrbridge/traducao#21]
Olá, percebi alguns erros de ortografia na wiki, mas não tenho permissão para alterações.

Vocês conseguiriam dar permissão geral (formato Wikipedia), ou apenas por usuário? Se for por usuário, o meu é @rogeriopradoj.

Valeu!

**Comment by alfsb** [comment]
On Wed, Apr 27, 2016 at 8:09 PM, Rogerio Prado de Jesus <
notifications@github.com> wrote:

> Olá, percebi alguns erros de ortografia na wiki, mas não tenho permissão
> para alterações.
>
> Vocês conseguiriam dar permissão geral (formato Wikipedia), ou apenas por
> usuário? Se for por usuário, o meu é @rogeriopradoj
> <https://github.com/rogeriopradoj>.
>
Tem como dar permissão por usuário e geral. Por enquanto estava no padrão,
que somente usuário membro pode editar. Já lhe acrescentei como membro para
editar.

Queria ver se tem como receber atualização do wiki por email. Com isso eu
já voto em abrir para edição de qualquer um com conta github.

André

**Comment by rogeriopradoj** [comment]
Valeu, @alfsb . Vou fazer edições agora, aí você já testa, ok?

Falou!

Rogério

**Comment by rogeriopradoj** [comment]
@alfsb talvez uma opção seja você monitorar o endereço git da wiki: https://github.com/phpdocbrbridge/traducao.wiki.git

Valeu

Rogério

**Comment by alfsb** [comment]
Ah, o wiki não precisa de teste, compilação. Se fala de editar diretamente os fontes do manual, daí o acesso que tenho de fazer é outro.

**Comment by rogeriopradoj** [comment]
Não, a ideia é editar a wiki mesmo. Meu voto também é deixar aberto para todo mundo que tenha conta no GitHub.

Falou

Rogério
