### ISSUE TITLE
Separar commits em pull requests diferentes?

### ISSUE THREAD

**Issue by AndersonMamede** [phpdocbrbridge/traducao#24]
Boa tarde!

Não tenho muita prática com GitHub ainda, mas gostaria de ajudar na tradução/atualização, então decidi fazer uma vez para me interar do processo.

Seguindo os artigos/tutoriais, fiz uma nova tradução (session-abort.xml), fiz commit e criei um pull request. Depois fiz uma atualização (apc-delete.xml) e segui o mesmo processo. Mas acontece que no phpdocbrbridge/traducao os commits ficaram juntos no mesmo pull request (#23).

Minha dúvida é: como separá-los em diferentes pull requests? Pois vendo o padrão utilizado, cada contexto seria um novo pull request, certo? Preciso criar UM branch para cada pull request? Ou então como seria feito?

Obrigado.

**Comment by rogeriopradoj** [comment]
Olá, @AndersonMamede , tudo bem?

> Preciso criar UM branch para cada pull request?

Sim!!! É uma convenção se você seguir vai te ajudar bastante!

Tendo branches separados, você pode mandar pull requests sem "misturar as coisas", além de deixar o branch "master" seu sempre pronto para ser sincronizado com o branch "master" deste repositório https://github.com/phpdocbrbridge/traducao/.

Se precisar de ajuda, pode me chamar!

Até mais!
Rogério

**Comment by AndersonMamede** [comment]
Eu havia lido sua resposta assim que você mandou, mas esqueci de te agradecer.
Obrigado pela ajuda @rogeriopradoj .
