### ISSUE TITLE
Traduzir exemplos?

### ISSUE THREAD

**Issue by AndersonMamede** [phpdocbrbridge/traducao#36]
Atualizei algumas traduções (#33), mas fiquei em dúvida em relação aos exemplos contidos nos arquivos xml.
Os comentários e mensagens que ficam no código de exemplo também devem ser traduzidos?

Exemplo do que me refiro:

```xml
<![CDATA[
<?php
// Connecting, selecting database <-TRADUZIR ESTE TEXTO?
$link = mysql_connect('mysql_host', 'mysql_user', 'mysql_password')
    or die('Could not connect: ' . mysql_error()); <-TRADUZIR ESTE TEXTO?
echo 'Connected successfully'; <-TRADUZIR ESTE TEXTO?
mysql_select_db('my_database') or die('Could not select database'); <-TRADUZIR ESTE TEXTO?

// Performing SQL query <-TRADUZIR ESTE TEXTO?
$query = 'SELECT * FROM my_table';
$result = mysql_query($query) or die('Query failed: ' . mysql_error()); <-TRADUZIR ESTE TEXTO?

// Printing results in HTML <-TRADUZIR ESTE TEXTO?
echo "<table>\n";
while ($line = mysql_fetch_array($result, MYSQL_ASSOC)) {
    echo "\t<tr>\n";
    foreach ($line as $col_value) {
        echo "\t\t<td>$col_value</td>\n";
    }
    echo "\t</tr>\n";
}
echo "</table>\n";

// Free resultset <-TRADUZIR ESTE TEXTO?
mysql_free_result($result);

// Closing connection <-TRADUZIR ESTE TEXTO?
mysql_close($link);
?>
]]>
`

**Comment by alfsb** [comment]
Sem muito padrão nessa questão. O que eu particularmente faço é traduzir comentários, mas evito traduzir dados exemplo.

Em parte porque tem exemplos grandes, e traduções parciais são fontes de bugs abertos contra a documentação, em parte porque as atualizações de tradução são frequentemente pontuais, o que daí evita que uma alteração num ponto não seja esquecida de ser feita em outros.

Daí, nesse exemplo, só traduziria os comentários depois de `//`, mas não os textos dentro de aspas e apóstrofos.

**Comment by AndersonMamede** [comment]
Entendi.
Vou fazer desta forma também.

Obrigado!
