### ISSUE TITLE
O que fazer em caso que necessite de correção?

### ISSUE THREAD

**Issue by Luc45-1n4c1o** [phpdocbrbridge/traducao#83]
Não é necessariamente uma tradução e sim uma correção da palavra. Vejam nos exemplos abaixo onde as palavras entre aspas seriam as corretas.
E.: temprario, "temporário", armazenmento, "armazenamento".

**Comment by alfsb** [comment]
Nesses casos basta localizar o arquivo e editar direto da interface do GitHub. Basicamente é seguir o [roteiro GitHub](https://github.com/phpdocbrbridge/traducao/wiki/Roteiro-GitHub). Fork, edita o arquivo, gera o pull request.

Não gera alteração na tag de revisão, apenas no corpo do arquivo.

Pode também abrir Issues para esses casos.
